# Generated by Django 4.0.3 on 2022-04-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_toiletreview_author_alter_toiletreview_stars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='toilet',
        ),
        migrations.AddField(
            model_name='toilet',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app.feature'),
        ),
    ]
