# Generated by Django 4.0.3 on 2022-04-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_feature_toilet_toilet_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='feature',
        ),
        migrations.AddField(
            model_name='toilet',
            name='feature',
            field=models.ManyToManyField(blank=True, null=True, related_name='features', to='app.feature'),
        ),
    ]
